program: examples.train.train_pdt
command:
  - nice
  - -n
  - 10
  - python3
  - -m
  - ${program}
  - --project
  - OSRL
  - --task
  - OfflineAntCircle-v0
  - --device
  - cuda
  - ${config}
  - ${args}
method: grid
name: pdt_sweep_AntCircle
project: OSRL
parameters:
  gamma:
    values: [0.99, 0.999]
  qr_weight:
    values: [1.0, 5.0]
  qc_weight:
    values: [0., 0.1, 1.0]
  seed:
    values: [0]
  critic_lr:
    values: [1e-4, 3e-4, 1e-3]
  
  # clip grad